export const PAU_DEPARTMENTS = [
  "Bilgisayar Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Makine Mühendisliği",
  "Endüstri Mühendisliği",
  "İnşaat Mühendisliği",
  "Gıda Mühendisliği",
  "Tekstil Mühendisliği",
  "Tıp Fakültesi",
  "Diş Hekimliği Fakültesi",
  "Hukuk Fakültesi",
  "İktisat",
  "İşletme",
  "Maliye",
  "Siyaset Bilimi ve Kamu Yönetimi",
  "Uluslararası Ticaret ve Finansman",
  "Yönetim Bilişim Sistemleri",
  "Psikoloji",
  "Sosyoloji",
  "Tarih",
  "Türk Dili ve Edebiyatı",
  "İngiliz Dili ve Edebiyatı",
  "Okul Öncesi Öğretmenliği",
  "Sınıf Öğretmenliği",
  "İngilizce Öğretmenliği",
  "Rehberlik ve Psikolojik Danışmanlık",
  "Gastronomi ve Mutfak Sanatları",
  "Turizm İşletmeciliği",
  "Hemşirelik",
  "Fizyoterapi ve Rehabilitasyon",
  "Spor Yöneticiliği",
  "Antrenörlük Eğitimi",
  "Müzik",
  "Resim",
  "Diğer"
].sort();

export const NAV_ITEMS = [
  { id: 'home', label: 'ANA SAYFA' },
  { id: 'features', label: 'ÖZELLİKLER' },
  { id: 'games', label: 'OYUNLAR' },
];